name: 'Composite Node Setup'
description: 'Composite Basic Node'
inputs:
  nodeVersion:
    required: false
    description: 'what node version to install'
    default: '12'
  npmToken:
    required: true
    description: 'token used for NPM authentication'
  ref:
    required: false
    description: 'ref to checkout'
    default: ''
  fetch-depth:
    required: false
    description: 'checkout fetch-depth'
    default: 1
  path:
    required: false
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
  clean:
    required: false
    description: 'Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching'
    default: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        clean: ${{ inputs.clean }}
    - name: Setup Node
      id: setup-node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}
    - name: Install NPM credentials
      id: install-npm-credentials
      run: |
        echo "::group::Install NPM Credentials"
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npmToken }}" >> ~/.npmrc
        echo "::endgroup::"
      shell: bash
    - name: Get yarn cache directory
      id: get-yarn-cache
      run: |
        echo "::group::Get yarn cache directory"
        echo "::set-output name=dir::$(yarn cache dir)"
        echo "::endgroup::"
      shell: bash
    - name: Restore yarn cache directory
      id: restore-yarn-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.get-yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: yarn install
      id: yarn-install
      run: |
        echo "::group::Yarn Install"
        yarn install --frozen-lockfile
        echo "::endgroup::"
      shell: bash
